### ISSUE TITLE
[BUG] "save&edit" button can't keep text that I type it before on widget

### ISSUE THREAD

**Issue by mojienjoyment** [TechbeeAT/jtxBoard#1086]
Describe the bug

When I click on + widget, it shows me a box that I write in it. When I tap "save&edit" button for more options, it shows me blank summary box but It should show me text that I write it before. See screenrecord for more accurate explanation. It happens sometimes

To Reproduce
1. Go to 'widget and tap on +'
2. Write any text and Click on 'save&edit'
4. See blank summary box

Expected behavior
 show me my text that write it before

Screenshots

https://github.com/TechbeeAT/jtxBoard/assets/68327458/7c0106f8-c499-4eab-8b07-61f295dbe216

** Log file **
[logs-2023-12-21-11-58-04.zip](https://github.com/TechbeeAT/jtxBoard/files/13739294/logs-2023-12-21-11-58-04.zip)

Device and version
 - Device: [Poco x3 pro]
 - Android version: [Android 14]
 - jtx Board version: [v2.6.5-beta01]
 - Downloaded from: [github]

**Comment by patrickunterwegs** [comment]
Hey @mojienjoyment , thank you for the feedback! Indeed it seems like the edit screen is opened before the entry is fully saved and then the summary/description are not loaded anymore. I'll check tonight!

By the way, if you have any issues with Farsi or in general with the right-to-left writing, please let me know and I'll have a look. 
I already made a bug on Google's side as the widget should also recognize the script and put it to the right, but the outcome was not satisfying. At least when you change the system settings to Farsi, it should also put the texts on the right side.

**Comment by patrickunterwegs** [comment]
Thanks again for the bug report. I'm just uploading a new version that should fix the issue. I'd be happy about a short feedback from your side as well.

**Comment by patrickunterwegs** [comment]
Sorry, it seemed solved on the emulator, now it appears again on my device, I need to investigate further

**Comment by mojienjoyment** [comment]
Yeah, It seems problem not solved. 
I have some improvement for RTL languages that open another issues for them

**Comment by patrickunterwegs** [comment]
beta03 is on the way, I hope I got it now. It was a bit more complicated than expected and seems to be related to a library upgrade as well.

**Comment by mojienjoyment** [comment]
> beta03 is on the way, I hope I got it now. It was a bit more complicated than expected and seems to be related to a library upgrade as well.

It seems works on beta03

**Comment by patrickunterwegs** [comment]
Thanks @mojienjoyment !
I also couldn't reproduce the problem anymore. I'll close the issue now.
