### ISSUE TITLE
[BUG] Cursor acts as tab when using external keyboard

### ISSUE THREAD

**Issue by tiptruck** [TechbeeAT/jtxBoard#580]
**Describe the bug**
Pressing the cursor (arrow) keys on an external bluetooth keyboard causes the cursor to move to the next input field.

**To Reproduce**
Connect bluetooth keyboard
Start adding/editing an entry
Press a cursor key
Cursor jumps to next field

**Expected Behaviour**
Cursor moves one step left or right on pressing horizontal arrows and to start/end of current field when vertical arrows are pressed.

**Device and version:**
 - Device: [e.g. Samsung Galaxy S22] Samsung tab S7 & A71_5g with two different keyboards
 - Android version [e.g. Android 11] 13
 - jtx Board version: [e.g. 2.1.0] 2.04.02.ose (204020005)
 - Downloaded from: [e.g. Google Play, f-Droid, ...] F-Droid

**Comment by patrickunterwegs** [comment]
I just reproduced this problem, it seems to be a general problem when using jetpack compose: 
https://stackoverflow.com/questions/75480217/jetpack-compose-moving-up-and-down-multiple-multi-line-basictextfields-with-phy

I'll investigate further to see if there is a solution.

**Comment by foss-** [comment]
Ran into this on Android 13.0, jtx Board 2.04.05.ose.

Makes it very hard to use an external keyboard. Since there is no way of currently accessing journal entries from desktop, external keyboard support would be highly welcome, allowing to properly write journal entries in an acceptable pace.

**Comment by tiptruck** [comment]
This looks to be fixed with the latest update.  Thank you

**Comment by foss-** [comment]
@tiptruck running 2.04.07.ose this is persisting for me. Which version resolves the problem for you?

**Comment by tiptruck** [comment]
This mornings update to 2.04.07.ose (205000003).

--
Craig Tipping,
When you stop learning, stop listening, stop looking and asking questions, always new questions, then it is time to die. - Lillian Eugenia Smith

-------- Original Message --------

**Comment by patrickunterwegs** [comment]
Thanks @tiptruck for the update.
@foss- was it also solved for you?
It might have been solved throught a library/dependency update...

**Comment by foss-** [comment]
Sadly not. As stated in my previous comment 2.04.07.ose does not resolve the issue for me. Restarted Android device because "have you tried turning it off and on again" but no dice.
Pressing arrow keys on external keyboard still tabs through page instead of navigating text in field with active cursor.

**Comment by foss-** [comment]
Should I open a new issue for the remaining problem or do you want to re-open this one here?

**Comment by patrickunterwegs** [comment]
Yes, let's ust reopen this one here 👍

**Comment by patrickunterwegs** [comment]
As it seems like Google still hasn't fixed this issue, I have opened in issue myself: 
https://issuetracker.google.com/issues/295666701

**Comment by tiptruck** [comment]
Dear Patrick,

I just created a new task with a multi-line description field and edited it with an external keyboard. I think this issue is fixed now.

Regards Craig

--
Craig Tipping,
When you stop learning, stop listening, stop looking and asking questions, always new questions, then it is time to die. - Lillian Eugenia Smith

-------- Original Message --------

**Comment by patrickunterwegs** [comment]
Hey Craig! Thank you for the update!
I tried it in the emulator and there it still doesn't work there. So maybe it was only solved by your keyboard provider? So I'd keep it open, let's see what Google has got to say about this issue!

**Comment by patrickunterwegs** [comment]
Finally Google admitted that the issue is on their side 😉 
https://issuetracker.google.com/issues/295666701?pli=1

Now somebody just needs to fix it on their side...

**Comment by patrickunterwegs** [comment]
Finally somebody marked this issue as fixed on Google's side =) Hopefully they will also provide a new version soon!
